
## resources
* [I am trask blog](http://iamtrask.github.io/)
* [Andrew Ng ML course](https://www.coursera.org/learn/machine-learning/)
* [Pedro domingos course](https://www.coursera.org/course/machlearning)

In [2]:
import numpy as np

## Work of a single neuron on a single example

In [45]:
def sigmoid(x,deriv=False):
    if deriv is True:
        return x*(1.-x)
    return 1./(1.+np.exp(-x))


X     = np.array([0,0,1])
y     = np.array([0])
alpha = 2.*np.random.random(3) - 1.
print 'Three features with values   ',X
print 'Target value                 ',y
print 'Random weights               ',alpha
print 'Value of activation function ',sigmoid(np.dot(X,alpha))

Three features with values    [0 0 1]
Target value                  [0]
Random weights                [ 0.59958265  0.51063332  0.6051716 ]
Value of activation function  0.646838593248


## Work of a single neuron on 4 examples

In [57]:
X     = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y     = np.array([[0,1,1,0]]).T

np.random.seed(1)
w0 = np.random.random((3,1))

print 'The data matrix (4 examples in 3 dimensions)\n',X
print '\n The target vector y\n',y
print '\nRandom weights \n',w0
print '\nValues of activation function\n',sigmoid(np.dot(X,w0))

The data matrix (4 examples in 3 dimensions)
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]

 The target vector y
[[0]
 [1]
 [1]
 [0]]

Random weights 
[[  4.17022005e-01]
 [  7.20324493e-01]
 [  1.14374817e-04]]

Values of activation function
[[ 0.50002859]
 [ 0.67270365]
 [ 0.60279781]
 [ 0.75721315]]


In [63]:
X     = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y     = np.array([[0,0,1,1]]).T

np.random.seed(1)
w0 = 2.0*np.random.random((3,1))-1.

for iter in xrange(10000):

    # forward propagation
    l0 = X
    l1 = sigmoid(np.dot(l0,w0))

    # how much did we miss?
    l1_error = y - l1

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * sigmoid(l1,True)

    # update weights
    w0 += np.dot(l0.T,l1_delta)

print "Output After Training:"
print l1


Output After Training:
[[ 0.00966449]
 [ 0.00786506]
 [ 0.99358898]
 [ 0.99211957]]
